const mentors = [
  {
    id: "1",
    name: "Jovan Cicmil",
    employment: "Software Development",
    role: "Mentor",
    avatar: "/assets/1.png",
  },
  {
    id: "2",
    name: "Tjaša Deu",
    employment: "Youtube",
    role: "Mentor, Panelista",
    avatar: "/assets/14.png",
  },
  {
    id: "3",
    name: "Ivan Radunović",
    employment: "Software Development",
    role: "Mentor, Panelista",
    avatar: "/assets/5.png",
  },
  {
    id: "4",
    name: "Nevena Korać",
    employment: "Digital Marketing",
    role: "Mentor, Panelista",
    avatar: "/assets/11.png",
  },
  {
    id: "5",
    name: "Ognjen Bulajić",
    employment: "Graphic Design",
    role: "Mentor, Panelista",
    avatar: "/assets/6.png",
  },
  {
    id: "6",
    name: "Ivan Blažević",
    employment: "Customer Support",
    role: "Mentor, Panelista",
    avatar: "/assets/16.png",
  },
  {
    id: "7",
    name: "Luka Žarić",
    employment: "Graphic Design",
    role: "Mentor",
    avatar: "/assets/7.png",
  },
  {
    id: "8",
    name: "Marko Čurović",
    employment: "Content Writing",
    role: "Mentor",
    avatar: "/assets/17.png",
  },
  {
    id: "9",
    name: "Tijana Ostojić",
    employment: "Content Writing",
    role: "Mentor",
    avatar: "/assets/10.png",
  },
  {
    id: "10",
    name: "Stevan Bogosavljević",
    employment: "Software Development",
    role: "Mentor",
    avatar: "/assets/3.png",
  },
  {
    id: "11",
    name: "Srđan Borović ",
    employment: "Digital Marketing",
    role: "Mentor",
    avatar: "/assets/12.png",
  },
  {
    id: "12",
    name: "Jovan Radnić",
    employment: "Digital Marketing",
    role: "Mentor",
    avatar: "/assets/13.png",
  },
  {
    id: "13",
    name: "Filip Vučković",
    employment: "Software Development",
    role: "Mentor",
    avatar: "/assets/15.png",
  },
  {
    id: "14",
    name: "Anđela Sekulić",
    employment: "Project management",
    role: "Mentor",
    avatar: "/assets/18.png",
  },
  {
    id: "15",
    name: "Dragan Čabarkapa",
    employment: "Software Development",
    role: "Mentor, Moderator",
    avatar: "/assets/2.png",
  },
];

export default mentors;
