const mentors = [
  {
    id: '1',
    name: 'Jovan Cicmil',
    employment: 'Software Development',
    role: 'Mentor',
    avatar: "/assets/1.png",
  },
  {
    id: '2',
    name: 'Dragan Čabarkapa',
    employment: 'Software Development',
    role: 'Mentor, Panelista, Moderator',
    avatar: "/assets/2.png",
  },
  {
    id: '3',
    name: 'Stevan Bogosavljević',
    employment: 'Software Development',
    role: 'Mentor',
    avatar: "/assets/3.png",
  },
  {
    id: '4',
    name: 'Filip Vučković',
    employment: 'Software Development',
    role: 'Mentor',
    avatar: "/assets/4.png",
  },
  {
    id: '5',
    name: 'Ivan Radunović',
    employment: 'Software Development',
    role: 'Panelista',
    avatar: "/assets/5.png",
  },
  {
    id: '6',
    name: 'Ognjen Bulajić',
    employment: 'Graphic Design',
    role: 'Mentor, Panelista',
    avatar: "/assets/6.png",
  },
  {
    id: '7',
    name: 'Luka Žarić',
    employment: 'Graphic Design',
    role: 'Mentor',
    avatar: "/assets/7.png",
  },
  {
    id: '8',
    name: 'Ivan Blažević',
    employment: 'Customer Support',
    role: 'Mentor, Panelista',
    avatar: "/assets/8.png",
  },
  {
    id: '9',
    name: 'Marko Čurović',
    employment: 'Content Writting',
    role: 'Mentor',
    avatar: "/assets/9.png",
  },
  {
    id: '10',
    name: 'Tijana Ostojić',
    employment: 'Content Writting',
    role: 'Mentor',
    avatar: "/assets/10.png",
  },
  {
    id: '11',
    name: 'Nevena Korać',
    employment: 'Digital Marketing',
    role: 'Mentor, Panelista',
    avatar: "/assets/11.png",
  },
  {
    id: '12',
    name: 'Srđan Borović ',
    employment: 'Digital Marketing',
    role: 'Mentor, Panelista',
    avatar: "/assets/12.png",
  },
  {
    id: '13',
    name: 'Jovan Radnić',
    employment: 'Digital Marketing',
    role: 'Mentor',
    avatar: "/assets/13.png",
  },
  {
    id: '14',
    name: 'Tjaša Deu',
    employment: 'Youtube',
    role: 'Panelista',
    avatar: "/assets/14.png",
  },
];

export default mentors;
